Build Debian package from a release tarball

diff --git a/utils/mkpstarball b/utils/mkpstarball
--- a/utils/mkpstarball
+++ b/utils/mkpstarball
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e # Abort on errors
 
 usage() {
   cat <<EOF
@@ -15,7 +16,9 @@ EOF
 }
 
 info() {
-  [ $VERBOSE -eq 1 ] && echo $*
+  if [ $VERBOSE -eq 1 ]; then
+    echo $*
+  fi
 }
 
 if [ -z "$PYSKOOL_HOME" ]; then
@@ -45,7 +48,7 @@ DISTDIR=${PYSKOOL_HOME}/dist
 mkdir -p $DISTDIR
 PKGNAME=pyskool-$VERSION
 ABSDIR=${DISTDIR}/$PKGNAME
-rm -rf ${ABSDIR}*
+rm -rf ${ABSDIR}
 DOCSDIR=${ABSDIR}/docs
 mkdir -p $DOCSDIR
 DOCSRC=${ABSDIR}/docs-src
