Add the 'pslpad' command to utils/psrelease

diff --git a/utils/psrelease b/utils/psrelease
--- a/utils/psrelease
+++ b/utils/psrelease
@@ -43,6 +43,7 @@ _require_skoolkit() {
     echo "Error: directory not found: $SKOOLKIT_HOME"
     exit 1
   fi
+  SKOOLKIT_TOOLS=$SKOOLKIT_HOME/tools
 }
 
 ###############################################################################
@@ -448,6 +449,27 @@ build_doczip() {
 }
 
 ###############################################################################
+# Update the Pyskool project on launchpad.net
+###############################################################################
+update_launchpad() {
+  _require_pyskool
+  _require_skoolkit
+
+  files=$(echo pyskool{-$VERSION{.tar.xz,.zip,-1.noarch.rpm},_$VERSION-1_all.deb})
+  echo -n "Checking files to upload: "
+  for f in $files; do
+    fname=$PYSKOOL_HOME/dist/$f
+    if [[ ! -f $fname ]]; then
+      echo "FAILED ($fname not found)"
+      exit 1
+    fi
+  done
+  echo "OK"
+
+  $SKOOLKIT_TOOLS/lputil.py --production --pyskool $VERSION
+}
+
+###############################################################################
 # Print usage information
 ###############################################################################
 usage() {
@@ -470,6 +492,7 @@ Post-release commands:
   bsdist - build a source package for uploading to PyPI
   ifpypi - verify that Pyskool can be installed from PyPI
   doczip - build a documentation zip archive for PyPI
+  pslpad - update the Pyskool project on launchpad.net
 EOM
 }
 
@@ -493,6 +516,7 @@ while [[ -n "$1" ]]; do
     bsdist) build_sdist ;;
     ifpypi) check_pypi ;;
     doczip) build_doczip ;;
+    pslpad) update_launchpad ;;
          *) echo "*** Unknown command '$1' ***"; usage ;;
   esac
   shift
